# -*- coding: utf-8 -*-


# This module records the constants used in the application


# Lines of each of the files header
NUM_CANDIDATES_LINE = 3
NUM_TITLES_LINE = 1

# Numbers for the candidates list
NUM_CANDIDATES_NAME = 0
NUM_CANDIDATES_FATHERS_TITLE = 1
NUM_CANDIDATES_MOTHERS_TITLES = 2
NUM_CANDIDATES_PARENTAL_GRANDFATHERS_TITLE = 3
NUM_CANDIDATES_PARENTAL_GRANDMOTHERS_TITLE = 4
NUM_CANDIDATES_MATERNAL_GRANDFATHERS_TITLE = 5
NUM_CANDIDATES_MATERNAL_GRANDMOTHERS_TITLE = 6

# Numbers for the titles list
NUM_TITLES_DEGREE = 0
NUM_TITLES_NAME_MASCULINE = 1
NUM_TITLES_NAME_FEMININE = 2
